# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system/ack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system/ack.proto',
  package='system',
  syntax='proto3',
  serialized_options=b'Z*github.com/airmap/interfaces/src/go/system',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10system/ack.proto\x12\x06system\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n\x03\x41\x63k\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12-\n\tsubmitted\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"T\n\x04Nack\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12-\n\tsubmitted\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06reason\x18\x03 \x01(\tB,Z*github.com/airmap/interfaces/src/go/systemb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='system.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='system.Ack.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='submitted', full_name='system.Ack.submitted', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=128,
)


_NACK = _descriptor.Descriptor(
  name='Nack',
  full_name='system.Nack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='system.Nack.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='submitted', full_name='system.Nack.submitted', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='system.Nack.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=214,
)

_ACK.fields_by_name['submitted'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_NACK.fields_by_name['submitted'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
DESCRIPTOR.message_types_by_name['Nack'] = _NACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'system.ack_pb2'
  # @@protoc_insertion_point(class_scope:system.Ack)
  })
_sym_db.RegisterMessage(Ack)

Nack = _reflection.GeneratedProtocolMessageType('Nack', (_message.Message,), {
  'DESCRIPTOR' : _NACK,
  '__module__' : 'system.ack_pb2'
  # @@protoc_insertion_point(class_scope:system.Nack)
  })
_sym_db.RegisterMessage(Nack)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
