// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ids/ids.proto

package ids

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Operator models the unique id of an operator.
type Operator struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bb53c9ac7a7c1b5, []int{0}
}

func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

// Operation models the unique id of an operation.
type Operation struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bb53c9ac7a7c1b5, []int{1}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

// USS models the unique id of a UTM Service Supplier (USS)
type USS struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *USS) Reset()         { *m = USS{} }
func (m *USS) String() string { return proto.CompactTextString(m) }
func (*USS) ProtoMessage()    {}
func (*USS) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bb53c9ac7a7c1b5, []int{2}
}

func (m *USS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_USS.Unmarshal(m, b)
}
func (m *USS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_USS.Marshal(b, m, deterministic)
}
func (m *USS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_USS.Merge(m, src)
}
func (m *USS) XXX_Size() int {
	return xxx_messageInfo_USS.Size(m)
}
func (m *USS) XXX_DiscardUnknown() {
	xxx_messageInfo_USS.DiscardUnknown(m)
}

var xxx_messageInfo_USS proto.InternalMessageInfo

func (m *USS) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

// Tracker models the unique id of a tracker.
type Tracker struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracker) Reset()         { *m = Tracker{} }
func (m *Tracker) String() string { return proto.CompactTextString(m) }
func (*Tracker) ProtoMessage()    {}
func (*Tracker) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bb53c9ac7a7c1b5, []int{3}
}

func (m *Tracker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracker.Unmarshal(m, b)
}
func (m *Tracker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracker.Marshal(b, m, deterministic)
}
func (m *Tracker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracker.Merge(m, src)
}
func (m *Tracker) XXX_Size() int {
	return xxx_messageInfo_Tracker.Size(m)
}
func (m *Tracker) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracker.DiscardUnknown(m)
}

var xxx_messageInfo_Tracker proto.InternalMessageInfo

func (m *Tracker) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

// Cluster models the unique id of a cluster
type Cluster struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bb53c9ac7a7c1b5, []int{4}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

func init() {
	proto.RegisterType((*Operator)(nil), "ids.Operator")
	proto.RegisterType((*Operation)(nil), "ids.Operation")
	proto.RegisterType((*USS)(nil), "ids.USS")
	proto.RegisterType((*Tracker)(nil), "ids.Tracker")
	proto.RegisterType((*Cluster)(nil), "ids.Cluster")
}

func init() { proto.RegisterFile("ids/ids.proto", fileDescriptor_9bb53c9ac7a7c1b5) }

var fileDescriptor_9bb53c9ac7a7c1b5 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xcf, 0x31, 0x0b, 0x82, 0x50,
	0x10, 0xc0, 0x71, 0x44, 0x28, 0x7d, 0xd0, 0xe2, 0x14, 0xb4, 0x84, 0x43, 0xda, 0xe2, 0x1b, 0xfa,
	0x06, 0xf5, 0x01, 0x82, 0xac, 0xa5, 0x25, 0xce, 0xe7, 0xcb, 0x8e, 0xd2, 0x93, 0xbb, 0xf3, 0xfb,
	0x47, 0xb6, 0xeb, 0xf8, 0x87, 0xdf, 0xf2, 0x37, 0x2b, 0xac, 0xc5, 0x62, 0x2d, 0x45, 0xcf, 0xa4,
	0x94, 0x84, 0x58, 0x4b, 0x9a, 0x99, 0xe8, 0xdc, 0x7b, 0x06, 0x25, 0x4e, 0x36, 0x26, 0x06, 0x79,
	0x88, 0x32, 0x76, 0xcd, 0x3a, 0xd8, 0x06, 0x79, 0x7c, 0x89, 0x40, 0xca, 0xb1, 0xd3, 0xdc, 0xc4,
	0x7f, 0x88, 0xd4, 0x4d, 0xcb, 0xd4, 0x84, 0xb7, 0xb2, 0x9c, 0x36, 0x3b, 0xb3, 0xbc, 0x32, 0xb8,
	0xb7, 0xe7, 0x59, 0x77, 0xfa, 0x0c, 0xa2, 0x33, 0xee, 0xb8, 0xbf, 0x67, 0x0d, 0xea, 0x6b, 0xa8,
	0x0a, 0x47, 0xad, 0x05, 0xe4, 0x16, 0x7a, 0x8b, 0x9d, 0x7a, 0x7e, 0x82, 0xf3, 0x62, 0x85, 0x9d,
	0x6d, 0xe8, 0x37, 0x5f, 0x2d, 0xc6, 0xfb, 0xc3, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xa7, 0x70,
	0xd9, 0x0e, 0x01, 0x00, 0x00,
}
