// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remoteid/remoteid.proto

package remoteid

import (
	context "context"
	fmt "fmt"
	geo "github.com/airmap/interfaces/src/go/geo"
	ids "github.com/airmap/interfaces/src/go/ids"
	measurements "github.com/airmap/interfaces/src/go/measurements"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Aircraft_Type int32

const (
	Aircraft_UNKNOWN                Aircraft_Type = 0
	Aircraft_AIRPLANE               Aircraft_Type = 1
	Aircraft_ROTORCRAFT             Aircraft_Type = 2
	Aircraft_GYROPLANE              Aircraft_Type = 3
	Aircraft_VTOL                   Aircraft_Type = 4
	Aircraft_ORNITHOPTER            Aircraft_Type = 5
	Aircraft_GLIDER                 Aircraft_Type = 6
	Aircraft_KITE                   Aircraft_Type = 7
	Aircraft_FREE_BALOON            Aircraft_Type = 8
	Aircraft_CAPTIVE_BALLOON        Aircraft_Type = 9
	Aircraft_AIRSHIP                Aircraft_Type = 10
	Aircraft_FREE_FALL_OR_PARACHUTE Aircraft_Type = 11
	Aircraft_ROCKET                 Aircraft_Type = 12
	Aircraft_GROUND_OBSTACLE        Aircraft_Type = 13
	Aircraft_OTHER                  Aircraft_Type = 14
)

var Aircraft_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "AIRPLANE",
	2:  "ROTORCRAFT",
	3:  "GYROPLANE",
	4:  "VTOL",
	5:  "ORNITHOPTER",
	6:  "GLIDER",
	7:  "KITE",
	8:  "FREE_BALOON",
	9:  "CAPTIVE_BALLOON",
	10: "AIRSHIP",
	11: "FREE_FALL_OR_PARACHUTE",
	12: "ROCKET",
	13: "GROUND_OBSTACLE",
	14: "OTHER",
}

var Aircraft_Type_value = map[string]int32{
	"UNKNOWN":                0,
	"AIRPLANE":               1,
	"ROTORCRAFT":             2,
	"GYROPLANE":              3,
	"VTOL":                   4,
	"ORNITHOPTER":            5,
	"GLIDER":                 6,
	"KITE":                   7,
	"FREE_BALOON":            8,
	"CAPTIVE_BALLOON":        9,
	"AIRSHIP":                10,
	"FREE_FALL_OR_PARACHUTE": 11,
	"ROCKET":                 12,
	"GROUND_OBSTACLE":        13,
	"OTHER":                  14,
}

func (x Aircraft_Type) String() string {
	return proto.EnumName(Aircraft_Type_name, int32(x))
}

func (Aircraft_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{5, 0}
}

// MonitorAreaParameters bundles parameters used in the MonitorOperationsArea
// rpc.
type MonitorAreaParameters struct {
	AreaOfInterest       *geo.BoundingBox `protobuf:"bytes,1,opt,name=area_of_interest,json=areaOfInterest,proto3" json:"area_of_interest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MonitorAreaParameters) Reset()         { *m = MonitorAreaParameters{} }
func (m *MonitorAreaParameters) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaParameters) ProtoMessage()    {}
func (*MonitorAreaParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{0}
}

func (m *MonitorAreaParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaParameters.Unmarshal(m, b)
}
func (m *MonitorAreaParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaParameters.Marshal(b, m, deterministic)
}
func (m *MonitorAreaParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaParameters.Merge(m, src)
}
func (m *MonitorAreaParameters) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaParameters.Size(m)
}
func (m *MonitorAreaParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaParameters.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaParameters proto.InternalMessageInfo

func (m *MonitorAreaParameters) GetAreaOfInterest() *geo.BoundingBox {
	if m != nil {
		return m.AreaOfInterest
	}
	return nil
}

type MonitorAreaResponse struct {
	// details is a discriminated union of response types
	//
	// Types that are valid to be assigned to Details:
	//	*MonitorAreaResponse_Added_
	//	*MonitorAreaResponse_Updated_
	//	*MonitorAreaResponse_Removed_
	//	*MonitorAreaResponse_Clustered_
	Details              isMonitorAreaResponse_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MonitorAreaResponse) Reset()         { *m = MonitorAreaResponse{} }
func (m *MonitorAreaResponse) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse) ProtoMessage()    {}
func (*MonitorAreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{1}
}

func (m *MonitorAreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse.Unmarshal(m, b)
}
func (m *MonitorAreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse.Marshal(b, m, deterministic)
}
func (m *MonitorAreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse.Merge(m, src)
}
func (m *MonitorAreaResponse) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse.Size(m)
}
func (m *MonitorAreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse proto.InternalMessageInfo

type isMonitorAreaResponse_Details interface {
	isMonitorAreaResponse_Details()
}

type MonitorAreaResponse_Added_ struct {
	Added *MonitorAreaResponse_Added `protobuf:"bytes,1,opt,name=added,proto3,oneof"`
}

type MonitorAreaResponse_Updated_ struct {
	Updated *MonitorAreaResponse_Updated `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type MonitorAreaResponse_Removed_ struct {
	Removed *MonitorAreaResponse_Removed `protobuf:"bytes,3,opt,name=removed,proto3,oneof"`
}

type MonitorAreaResponse_Clustered_ struct {
	Clustered *MonitorAreaResponse_Clustered `protobuf:"bytes,4,opt,name=clustered,proto3,oneof"`
}

func (*MonitorAreaResponse_Added_) isMonitorAreaResponse_Details() {}

func (*MonitorAreaResponse_Updated_) isMonitorAreaResponse_Details() {}

func (*MonitorAreaResponse_Removed_) isMonitorAreaResponse_Details() {}

func (*MonitorAreaResponse_Clustered_) isMonitorAreaResponse_Details() {}

func (m *MonitorAreaResponse) GetDetails() isMonitorAreaResponse_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *MonitorAreaResponse) GetAdded() *MonitorAreaResponse_Added {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Added_); ok {
		return x.Added
	}
	return nil
}

func (m *MonitorAreaResponse) GetUpdated() *MonitorAreaResponse_Updated {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Updated_); ok {
		return x.Updated
	}
	return nil
}

func (m *MonitorAreaResponse) GetRemoved() *MonitorAreaResponse_Removed {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Removed_); ok {
		return x.Removed
	}
	return nil
}

func (m *MonitorAreaResponse) GetClustered() *MonitorAreaResponse_Clustered {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Clustered_); ok {
		return x.Clustered
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MonitorAreaResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MonitorAreaResponse_Added_)(nil),
		(*MonitorAreaResponse_Updated_)(nil),
		(*MonitorAreaResponse_Removed_)(nil),
		(*MonitorAreaResponse_Clustered_)(nil),
	}
}

// Added models an operation that has entered the monitored area.
type MonitorAreaResponse_Added struct {
	Operation            *Operation        `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Positions            []*geo.Position4D `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MonitorAreaResponse_Added) Reset()         { *m = MonitorAreaResponse_Added{} }
func (m *MonitorAreaResponse_Added) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Added) ProtoMessage()    {}
func (*MonitorAreaResponse_Added) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{1, 0}
}

func (m *MonitorAreaResponse_Added) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Added.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Added) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Added.Marshal(b, m, deterministic)
}
func (m *MonitorAreaResponse_Added) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Added.Merge(m, src)
}
func (m *MonitorAreaResponse_Added) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Added.Size(m)
}
func (m *MonitorAreaResponse_Added) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Added.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Added proto.InternalMessageInfo

func (m *MonitorAreaResponse_Added) GetOperation() *Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *MonitorAreaResponse_Added) GetPositions() []*geo.Position4D {
	if m != nil {
		return m.Positions
	}
	return nil
}

// Updated models an operation that has been updated in the monitored area.
type MonitorAreaResponse_Updated struct {
	// details is a discriminated union of update types
	//
	// Types that are valid to be assigned to Details:
	//	*MonitorAreaResponse_Updated_Operation
	//	*MonitorAreaResponse_Updated_State
	Details              isMonitorAreaResponse_Updated_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *MonitorAreaResponse_Updated) Reset()         { *m = MonitorAreaResponse_Updated{} }
func (m *MonitorAreaResponse_Updated) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Updated) ProtoMessage()    {}
func (*MonitorAreaResponse_Updated) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{1, 1}
}

func (m *MonitorAreaResponse_Updated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Updated.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Updated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Updated.Marshal(b, m, deterministic)
}
func (m *MonitorAreaResponse_Updated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Updated.Merge(m, src)
}
func (m *MonitorAreaResponse_Updated) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Updated.Size(m)
}
func (m *MonitorAreaResponse_Updated) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Updated.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Updated proto.InternalMessageInfo

type isMonitorAreaResponse_Updated_Details interface {
	isMonitorAreaResponse_Updated_Details()
}

type MonitorAreaResponse_Updated_Operation struct {
	Operation *Operation `protobuf:"bytes,1,opt,name=operation,proto3,oneof"`
}

type MonitorAreaResponse_Updated_State struct {
	State *Operation_State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

func (*MonitorAreaResponse_Updated_Operation) isMonitorAreaResponse_Updated_Details() {}

func (*MonitorAreaResponse_Updated_State) isMonitorAreaResponse_Updated_Details() {}

func (m *MonitorAreaResponse_Updated) GetDetails() isMonitorAreaResponse_Updated_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *MonitorAreaResponse_Updated) GetOperation() *Operation {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Updated_Operation); ok {
		return x.Operation
	}
	return nil
}

func (m *MonitorAreaResponse_Updated) GetState() *Operation_State {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Updated_State); ok {
		return x.State
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MonitorAreaResponse_Updated) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MonitorAreaResponse_Updated_Operation)(nil),
		(*MonitorAreaResponse_Updated_State)(nil),
	}
}

// Removed models an operation that has been removed from the monitored area.
type MonitorAreaResponse_Removed struct {
	Id                   *ids.Operation `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MonitorAreaResponse_Removed) Reset()         { *m = MonitorAreaResponse_Removed{} }
func (m *MonitorAreaResponse_Removed) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Removed) ProtoMessage()    {}
func (*MonitorAreaResponse_Removed) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{1, 2}
}

func (m *MonitorAreaResponse_Removed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Removed.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Removed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Removed.Marshal(b, m, deterministic)
}
func (m *MonitorAreaResponse_Removed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Removed.Merge(m, src)
}
func (m *MonitorAreaResponse_Removed) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Removed.Size(m)
}
func (m *MonitorAreaResponse_Removed) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Removed.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Removed proto.InternalMessageInfo

func (m *MonitorAreaResponse_Removed) GetId() *ids.Operation {
	if m != nil {
		return m.Id
	}
	return nil
}

// Clustered models a collection of multiple operation that are in near
// proximity to each other. If a cluster contains only one operation, the
// center of the cluster represents an obfuscated position and not the actual
// position of the operation.
type MonitorAreaResponse_Clustered struct {
	Clusters             []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MonitorAreaResponse_Clustered) Reset()         { *m = MonitorAreaResponse_Clustered{} }
func (m *MonitorAreaResponse_Clustered) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Clustered) ProtoMessage()    {}
func (*MonitorAreaResponse_Clustered) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{1, 3}
}

func (m *MonitorAreaResponse_Clustered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Clustered.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Clustered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Clustered.Marshal(b, m, deterministic)
}
func (m *MonitorAreaResponse_Clustered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Clustered.Merge(m, src)
}
func (m *MonitorAreaResponse_Clustered) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Clustered.Size(m)
}
func (m *MonitorAreaResponse_Clustered) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Clustered.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Clustered proto.InternalMessageInfo

func (m *MonitorAreaResponse_Clustered) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

// Operation models an aerial operation in a given area.
type Operation struct {
	Id                   *ids.Operation `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Operator             *Operator      `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Aircraft             *Aircraft      `protobuf:"bytes,3,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	Geometry             *geo.Polygon   `protobuf:"bytes,4,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Purpose              string         `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Simulated            bool           `protobuf:"varint,6,opt,name=simulated,proto3" json:"simulated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{2}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() *ids.Operation {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Operation) GetOperator() *Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *Operation) GetAircraft() *Aircraft {
	if m != nil {
		return m.Aircraft
	}
	return nil
}

func (m *Operation) GetGeometry() *geo.Polygon {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Operation) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Operation) GetSimulated() bool {
	if m != nil {
		return m.Simulated
	}
	return false
}

// State models an operation's current state
type Operation_State struct {
	Id                   *ids.Operation                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp            `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Position             *measurements.Position_Absolute `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *measurements.Velocity_Polar    `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Operation_State) Reset()         { *m = Operation_State{} }
func (m *Operation_State) String() string { return proto.CompactTextString(m) }
func (*Operation_State) ProtoMessage()    {}
func (*Operation_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{2, 0}
}

func (m *Operation_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation_State.Unmarshal(m, b)
}
func (m *Operation_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation_State.Marshal(b, m, deterministic)
}
func (m *Operation_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation_State.Merge(m, src)
}
func (m *Operation_State) XXX_Size() int {
	return xxx_messageInfo_Operation_State.Size(m)
}
func (m *Operation_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation_State.DiscardUnknown(m)
}

var xxx_messageInfo_Operation_State proto.InternalMessageInfo

func (m *Operation_State) GetId() *ids.Operation {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Operation_State) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Operation_State) GetPosition() *measurements.Position_Absolute {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Operation_State) GetVelocity() *measurements.Velocity_Polar {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Cluster struct {
	Id                   *ids.Cluster `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Geometry             *geo.Polygon `protobuf:"bytes,2,opt,name=geometry,proto3" json:"geometry,omitempty"`
	NumberOfOperations   int32        `protobuf:"varint,3,opt,name=number_of_operations,json=numberOfOperations,proto3" json:"number_of_operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{3}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetId() *ids.Cluster {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Cluster) GetGeometry() *geo.Polygon {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Cluster) GetNumberOfOperations() int32 {
	if m != nil {
		return m.NumberOfOperations
	}
	return 0
}

// Operator models the operator of an aircraft
type Operator struct {
	Id                   *ids.Operator     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location             *geo.Coordinate2D `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{4}
}

func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetId() *ids.Operator {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Operator) GetLocation() *geo.Coordinate2D {
	if m != nil {
		return m.Location
	}
	return nil
}

// Aircraft models the vehicle performing an operation.
type Aircraft struct {
	Type                 Aircraft_Type `protobuf:"varint,1,opt,name=type,proto3,enum=remoteid.Aircraft_Type" json:"type,omitempty"`
	Serial               string        `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	Registration         string        `protobuf:"bytes,5,opt,name=registration,proto3" json:"registration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Aircraft) Reset()         { *m = Aircraft{} }
func (m *Aircraft) String() string { return proto.CompactTextString(m) }
func (*Aircraft) ProtoMessage()    {}
func (*Aircraft) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ec874c18515d49f, []int{5}
}

func (m *Aircraft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aircraft.Unmarshal(m, b)
}
func (m *Aircraft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aircraft.Marshal(b, m, deterministic)
}
func (m *Aircraft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aircraft.Merge(m, src)
}
func (m *Aircraft) XXX_Size() int {
	return xxx_messageInfo_Aircraft.Size(m)
}
func (m *Aircraft) XXX_DiscardUnknown() {
	xxx_messageInfo_Aircraft.DiscardUnknown(m)
}

var xxx_messageInfo_Aircraft proto.InternalMessageInfo

func (m *Aircraft) GetType() Aircraft_Type {
	if m != nil {
		return m.Type
	}
	return Aircraft_UNKNOWN
}

func (m *Aircraft) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Aircraft) GetRegistration() string {
	if m != nil {
		return m.Registration
	}
	return ""
}

func init() {
	proto.RegisterEnum("remoteid.Aircraft_Type", Aircraft_Type_name, Aircraft_Type_value)
	proto.RegisterType((*MonitorAreaParameters)(nil), "remoteid.MonitorAreaParameters")
	proto.RegisterType((*MonitorAreaResponse)(nil), "remoteid.MonitorAreaResponse")
	proto.RegisterType((*MonitorAreaResponse_Added)(nil), "remoteid.MonitorAreaResponse.Added")
	proto.RegisterType((*MonitorAreaResponse_Updated)(nil), "remoteid.MonitorAreaResponse.Updated")
	proto.RegisterType((*MonitorAreaResponse_Removed)(nil), "remoteid.MonitorAreaResponse.Removed")
	proto.RegisterType((*MonitorAreaResponse_Clustered)(nil), "remoteid.MonitorAreaResponse.Clustered")
	proto.RegisterType((*Operation)(nil), "remoteid.Operation")
	proto.RegisterType((*Operation_State)(nil), "remoteid.Operation.State")
	proto.RegisterType((*Cluster)(nil), "remoteid.Cluster")
	proto.RegisterType((*Operator)(nil), "remoteid.Operator")
	proto.RegisterType((*Aircraft)(nil), "remoteid.Aircraft")
}

func init() { proto.RegisterFile("remoteid/remoteid.proto", fileDescriptor_6ec874c18515d49f) }

var fileDescriptor_6ec874c18515d49f = []byte{
	// 988 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xcf, 0x6f, 0xdb, 0x36,
	0x14, 0xc7, 0x63, 0xc7, 0x8e, 0xa5, 0xe7, 0xfc, 0x50, 0x99, 0xad, 0xf5, 0x8c, 0x74, 0x09, 0x3c,
	0x0c, 0xcb, 0xb0, 0x45, 0x6e, 0xd3, 0x1d, 0x8a, 0xf6, 0x24, 0x3b, 0x4e, 0x6c, 0xc4, 0xb3, 0x0c,
	0x46, 0xc9, 0x7e, 0x1d, 0x0c, 0xc5, 0xa2, 0x3d, 0x02, 0x96, 0x29, 0x90, 0x74, 0xb1, 0x00, 0xbb,
	0xed, 0x9f, 0xdb, 0x9f, 0xb0, 0xf3, 0xce, 0xfb, 0x13, 0x76, 0x18, 0x48, 0x51, 0x92, 0xb3, 0x06,
	0x69, 0x6f, 0x22, 0xf9, 0x79, 0x8f, 0xfc, 0x7e, 0xf9, 0xf4, 0x08, 0xcf, 0x38, 0x89, 0x99, 0x24,
	0x34, 0x6a, 0x67, 0x1f, 0x6e, 0xc2, 0x99, 0x64, 0xc8, 0xca, 0xc6, 0xcd, 0x1d, 0x1a, 0x89, 0x36,
	0x8d, 0x44, 0xba, 0xd0, 0xdc, 0x99, 0x13, 0xd6, 0x9e, 0x13, 0x66, 0x86, 0x87, 0x31, 0x09, 0xc5,
	0x8a, 0x93, 0x98, 0x2c, 0xa5, 0x68, 0xaf, 0x0f, 0x32, 0x60, 0xce, 0xd8, 0x7c, 0x41, 0xda, 0x7a,
	0x74, 0xbb, 0x9a, 0xb5, 0x25, 0x8d, 0x89, 0x90, 0x61, 0x9c, 0xa4, 0x40, 0xeb, 0x0a, 0x3e, 0xfd,
	0x9e, 0x2d, 0xa9, 0x64, 0xdc, 0xe3, 0x24, 0x1c, 0x87, 0x3c, 0x8c, 0x89, 0x24, 0x5c, 0xa0, 0x37,
	0xe0, 0x84, 0x9c, 0x84, 0x13, 0x36, 0x9b, 0xd0, 0xa5, 0x24, 0x9c, 0x08, 0xd9, 0x28, 0x1d, 0x95,
	0x8e, 0xeb, 0xa7, 0x8e, 0xab, 0x0e, 0xd0, 0x61, 0xab, 0x65, 0x44, 0x97, 0xf3, 0x0e, 0xfb, 0x0d,
	0xef, 0x2a, 0xd2, 0x9f, 0x0d, 0x0c, 0xd7, 0xfa, 0xb7, 0x02, 0xfb, 0x6b, 0x59, 0x31, 0x11, 0x09,
	0x5b, 0x0a, 0x82, 0xde, 0x42, 0x35, 0x8c, 0x22, 0x12, 0x99, 0x44, 0x5f, 0xb8, 0xb9, 0xec, 0x07,
	0x68, 0xd7, 0x53, 0x68, 0x7f, 0x03, 0xa7, 0x31, 0xc8, 0x83, 0xda, 0x2a, 0x89, 0x42, 0x49, 0xa2,
	0x46, 0x59, 0x87, 0x7f, 0xf9, 0x78, 0xf8, 0x75, 0x0a, 0xf7, 0x37, 0x70, 0x16, 0xa7, 0x52, 0xa8,
	0x90, 0x77, 0x24, 0x6a, 0x6c, 0x7e, 0x4c, 0x0a, 0x9c, 0xc2, 0x2a, 0x85, 0x89, 0x43, 0x17, 0x60,
	0x4f, 0x17, 0x2b, 0xa1, 0x84, 0x46, 0x8d, 0x8a, 0x4e, 0xf2, 0xd5, 0xe3, 0x49, 0xba, 0x19, 0xde,
	0xdf, 0xc0, 0x45, 0x6c, 0x93, 0x42, 0x55, 0x0b, 0x44, 0x2f, 0xc1, 0x66, 0x09, 0xe1, 0xa1, 0xa4,
	0x6c, 0x69, 0x8c, 0xd9, 0x2f, 0x32, 0xfa, 0xd9, 0x12, 0x2e, 0x28, 0x74, 0x02, 0x76, 0xc2, 0x04,
	0x55, 0xdf, 0xa2, 0x51, 0x3e, 0xda, 0x3c, 0xae, 0x9f, 0xee, 0xe9, 0x4b, 0x19, 0x9b, 0xd9, 0xef,
	0xce, 0x70, 0x41, 0x34, 0x7f, 0x87, 0x9a, 0x31, 0x03, 0xbd, 0xfa, 0xb8, 0xcd, 0xd4, 0x51, 0x8b,
	0xed, 0x5e, 0x42, 0x55, 0xc8, 0x50, 0x12, 0xe3, 0xfb, 0x67, 0x0f, 0x04, 0xb8, 0x57, 0x0a, 0x50,
	0x97, 0xa5, 0xc9, 0x8e, 0x0d, 0xb5, 0x88, 0xc8, 0x90, 0x2e, 0x44, 0xf3, 0x6b, 0xa8, 0x19, 0x1f,
	0xd1, 0xe7, 0x50, 0xa6, 0xd9, 0xe5, 0xef, 0xba, 0xaa, 0xaa, 0x0b, 0x79, 0x65, 0x1a, 0x35, 0xdf,
	0x80, 0x9d, 0xbb, 0x85, 0x4e, 0xc0, 0x32, 0x6e, 0x89, 0x46, 0x49, 0x6b, 0x7c, 0x52, 0x6c, 0x6c,
	0x30, 0x9c, 0x23, 0x6b, 0x3b, 0xb6, 0xfe, 0xdc, 0x04, 0x3b, 0x4f, 0xfc, 0xa1, 0x4d, 0x91, 0x0b,
	0x56, 0x2a, 0x95, 0x71, 0x23, 0x10, 0xfd, 0x5f, 0x20, 0xe3, 0x38, 0x67, 0x14, 0x1f, 0x52, 0x3e,
	0xe5, 0xe1, 0x4c, 0x9a, 0x2a, 0x5a, 0xe3, 0x3d, 0xb3, 0x82, 0x73, 0x06, 0x1d, 0x83, 0x35, 0x27,
	0x2c, 0x26, 0x92, 0xdf, 0x99, 0x82, 0xd9, 0x36, 0x77, 0xb5, 0xb8, 0x9b, 0xb3, 0x25, 0xce, 0x57,
	0x51, 0x03, 0x6a, 0xc9, 0x8a, 0x27, 0x4c, 0x90, 0x46, 0xf5, 0xa8, 0x74, 0x6c, 0xe3, 0x6c, 0x88,
	0x0e, 0xc0, 0x16, 0x34, 0x5e, 0x2d, 0x74, 0xf5, 0x6f, 0x1d, 0x95, 0x8e, 0x2d, 0x5c, 0x4c, 0x34,
	0xff, 0x2a, 0x41, 0x55, 0xfb, 0xff, 0x41, 0xad, 0xaf, 0xc1, 0xce, 0x1b, 0x80, 0x11, 0xdb, 0x74,
	0xd3, 0x16, 0xe1, 0x66, 0x2d, 0xc2, 0x0d, 0x32, 0x02, 0x17, 0x30, 0x7a, 0x0b, 0x56, 0x56, 0x50,
	0x46, 0xf5, 0xa1, 0x7b, 0xaf, 0xdf, 0x64, 0xa5, 0xe7, 0x7a, 0xb7, 0x82, 0x2d, 0x56, 0x92, 0xe0,
	0x3c, 0x00, 0xbd, 0x06, 0xeb, 0x1d, 0x59, 0xb0, 0x29, 0x95, 0x99, 0x05, 0x07, 0xf7, 0x83, 0x6f,
	0xcc, 0xaa, 0x32, 0x25, 0xe4, 0x38, 0xa7, 0x5b, 0x7f, 0x94, 0xa0, 0x66, 0xee, 0x1a, 0x1d, 0xac,
	0x89, 0xdb, 0xd6, 0xe2, 0xb2, 0x2a, 0x50, 0xd2, 0xd6, 0x6d, 0x2e, 0x3f, 0x6a, 0xf3, 0x0b, 0xf8,
	0x64, 0xb9, 0x8a, 0x6f, 0x09, 0x57, 0xbd, 0x2d, 0xaf, 0x72, 0xa1, 0x65, 0x55, 0x31, 0x4a, 0xd7,
	0xfc, 0x59, 0xee, 0x9c, 0x68, 0xfd, 0x08, 0x56, 0x56, 0x08, 0xe8, 0xf9, 0xda, 0x29, 0x76, 0xd6,
	0x2c, 0x66, 0xe9, 0x31, 0x4e, 0xc0, 0x5a, 0xb0, 0x69, 0xfa, 0x7f, 0xa5, 0xc7, 0x78, 0xa2, 0x8f,
	0xd1, 0x65, 0x8c, 0x47, 0x74, 0x19, 0x4a, 0x72, 0x7a, 0x86, 0x73, 0xa4, 0xf5, 0x77, 0x19, 0xac,
	0xac, 0x66, 0xd0, 0x37, 0x50, 0x91, 0x77, 0x09, 0xd1, 0xc9, 0x77, 0x4f, 0x9f, 0xbd, 0x5f, 0x55,
	0x6e, 0x70, 0x97, 0x10, 0xac, 0x21, 0xf4, 0x14, 0xb6, 0x04, 0xe1, 0x34, 0x5c, 0x68, 0x47, 0x6d,
	0x6c, 0x46, 0xa8, 0x05, 0xdb, 0x9c, 0xcc, 0xa9, 0x90, 0xe6, 0x27, 0x4f, 0x2b, 0xe9, 0xde, 0x5c,
	0xeb, 0x9f, 0x12, 0x54, 0x54, 0x2a, 0x54, 0x87, 0xda, 0xf5, 0xe8, 0x72, 0xe4, 0xff, 0x30, 0x72,
	0x36, 0xd0, 0x36, 0x58, 0xde, 0x00, 0x8f, 0x87, 0xde, 0xa8, 0xe7, 0x94, 0xd0, 0x2e, 0x00, 0xf6,
	0x03, 0x1f, 0x77, 0xb1, 0x77, 0x1e, 0x38, 0x65, 0xb4, 0x03, 0xf6, 0xc5, 0x4f, 0xd8, 0x4f, 0x97,
	0x37, 0x91, 0x05, 0x95, 0x9b, 0xc0, 0x1f, 0x3a, 0x15, 0xb4, 0x07, 0x75, 0x1f, 0x8f, 0x06, 0x41,
	0xdf, 0x1f, 0x07, 0x3d, 0xec, 0x54, 0x11, 0xc0, 0xd6, 0xc5, 0x70, 0x70, 0xd6, 0xc3, 0xce, 0x96,
	0xc2, 0x2e, 0x07, 0x41, 0xcf, 0xa9, 0x29, 0xec, 0x1c, 0xf7, 0x7a, 0x93, 0x8e, 0x37, 0xf4, 0xfd,
	0x91, 0x63, 0xa1, 0x7d, 0xd8, 0xeb, 0x7a, 0xe3, 0x60, 0x70, 0xa3, 0xe7, 0xf4, 0xa4, 0xad, 0x0e,
	0xe4, 0x0d, 0xf0, 0x55, 0x7f, 0x30, 0x76, 0x00, 0x35, 0xe1, 0xa9, 0x0e, 0x39, 0xf7, 0x86, 0xc3,
	0x89, 0x8f, 0x27, 0x63, 0x0f, 0x7b, 0xdd, 0xfe, 0x75, 0xd0, 0x73, 0xea, 0x6a, 0x13, 0xec, 0x77,
	0x2f, 0x7b, 0x81, 0xb3, 0xad, 0x32, 0x5d, 0x60, 0xff, 0x7a, 0x74, 0x36, 0xf1, 0x3b, 0x57, 0x81,
	0xd7, 0x1d, 0xf6, 0x9c, 0x1d, 0x64, 0x43, 0xd5, 0x0f, 0xfa, 0x3d, 0xec, 0xec, 0x9e, 0xfe, 0x02,
	0x16, 0xd6, 0x56, 0x0e, 0xce, 0x90, 0x0f, 0xf5, 0xb5, 0x26, 0x8d, 0x0e, 0x1f, 0xec, 0xdd, 0xc5,
	0x33, 0xd8, 0x7c, 0xfe, 0x68, 0x73, 0x7f, 0x51, 0xea, 0xb8, 0x3f, 0x7f, 0x3b, 0xa7, 0xf2, 0xd7,
	0xd5, 0xad, 0x3b, 0x65, 0x71, 0x3b, 0xa4, 0x3c, 0x0e, 0x93, 0xb6, 0x7e, 0x31, 0x67, 0xe1, 0x94,
	0x88, 0xb6, 0xe0, 0xd3, 0xf6, 0x9c, 0xe5, 0x0f, 0xfc, 0xed, 0x96, 0xfe, 0xcf, 0x5e, 0xfd, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xf9, 0x28, 0x55, 0xa9, 0xfc, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteIDClient is the client API for RemoteID service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteIDClient interface {
	// EXPERIMENTAL: API subject to change
	// MonitorArea monitors a given area for active operations.
	MonitorArea(ctx context.Context, in *MonitorAreaParameters, opts ...grpc.CallOption) (RemoteID_MonitorAreaClient, error)
}

type remoteIDClient struct {
	cc *grpc.ClientConn
}

func NewRemoteIDClient(cc *grpc.ClientConn) RemoteIDClient {
	return &remoteIDClient{cc}
}

func (c *remoteIDClient) MonitorArea(ctx context.Context, in *MonitorAreaParameters, opts ...grpc.CallOption) (RemoteID_MonitorAreaClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteID_serviceDesc.Streams[0], "/remoteid.RemoteID/MonitorArea", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteIDMonitorAreaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteID_MonitorAreaClient interface {
	Recv() (*MonitorAreaResponse, error)
	grpc.ClientStream
}

type remoteIDMonitorAreaClient struct {
	grpc.ClientStream
}

func (x *remoteIDMonitorAreaClient) Recv() (*MonitorAreaResponse, error) {
	m := new(MonitorAreaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoteIDServer is the server API for RemoteID service.
type RemoteIDServer interface {
	// EXPERIMENTAL: API subject to change
	// MonitorArea monitors a given area for active operations.
	MonitorArea(*MonitorAreaParameters, RemoteID_MonitorAreaServer) error
}

// UnimplementedRemoteIDServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteIDServer struct {
}

func (*UnimplementedRemoteIDServer) MonitorArea(req *MonitorAreaParameters, srv RemoteID_MonitorAreaServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorArea not implemented")
}

func RegisterRemoteIDServer(s *grpc.Server, srv RemoteIDServer) {
	s.RegisterService(&_RemoteID_serviceDesc, srv)
}

func _RemoteID_MonitorArea_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorAreaParameters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteIDServer).MonitorArea(m, &remoteIDMonitorAreaServer{stream})
}

type RemoteID_MonitorAreaServer interface {
	Send(*MonitorAreaResponse) error
	grpc.ServerStream
}

type remoteIDMonitorAreaServer struct {
	grpc.ServerStream
}

func (x *remoteIDMonitorAreaServer) Send(m *MonitorAreaResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RemoteID_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remoteid.RemoteID",
	HandlerType: (*RemoteIDServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorArea",
			Handler:       _RemoteID_MonitorArea_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remoteid/remoteid.proto",
}
