# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geo/geo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import extensions_pb2 as extensions__pb2
from units import units_pb2 as units_dot_units__pb2
from units import units_ext_pb2 as units_dot_units__ext__pb2
from measurements import measurements_pb2 as measurements_dot_measurements__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geo/geo.proto',
  package='geo',
  syntax='proto3',
  serialized_options=_b('Z\'github.com/airmap/interfaces/src/go/geo'),
  serialized_pb=_b('\n\rgeo/geo.proto\x12\x03geo\x1a\x10\x65xtensions.proto\x1a\x11units/units.proto\x1a\x15units/units_ext.proto\x1a\x1fmeasurements/measurements.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x02\n\x0c\x43oordinate2D\x12<\n\x08latitude\x18\x01 \x01(\x0b\x32\x0e.units.DegreesB\x1a\x9a\xa6\x1d\t\t\x00\x00\x00\x00\x00\x80V\xc0\xa2\xa6\x1d\t\t\x00\x00\x00\x00\x00\x80V@\x12=\n\tlongitude\x18\x02 \x01(\x0b\x32\x0e.units.DegreesB\x1a\x9a\xa6\x1d\t\t\x00\x00\x00\x00\x00\x80\x66\xc0\xa2\xa6\x1d\t\t\x00\x00\x00\x00\x00\x80\x66@\x12,\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x17.geo.Coordinate2D.ErrorB\x04\x80\xa6\x1d\x01\x1aj\n\x05\x45rror\x12/\n\x08latitude\x18\x01 \x01(\x0b\x32\x0e.units.DegreesB\r\x9a\xa6\x1d\t\t\x00\x00\x00\x00\x00\x00\x00\x00\x12\x30\n\tlongitude\x18\x02 \x01(\x0b\x32\x0e.units.DegreesB\r\x9a\xa6\x1d\t\t\x00\x00\x00\x00\x00\x00\x00\x00\"n\n\nPosition4D\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x08position\x18\x02 \x01(\x0b\x32\x1f.measurements.Position.Absolute\"Y\n\x0b\x42oundingBox\x12$\n\tsouthwest\x18\x01 \x01(\x0b\x32\x11.geo.Coordinate2D\x12$\n\tnortheast\x18\x02 \x01(\x0b\x32\x11.geo.Coordinate2D\"4\n\nLinearRing\x12&\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x11.geo.Coordinate2D\")\n\x07Polygon\x12\x1e\n\x05rings\x18\x01 \x03(\x0b\x32\x0f.geo.LinearRingB)Z\'github.com/airmap/interfaces/src/go/geob\x06proto3')
  ,
  dependencies=[extensions__pb2.DESCRIPTOR,units_dot_units__pb2.DESCRIPTOR,units_dot_units__ext__pb2.DESCRIPTOR,measurements_dot_measurements__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_COORDINATE2D_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='geo.Coordinate2D.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='geo.Coordinate2D.Error.latitude', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\232\246\035\t\t\000\000\000\000\000\000\000\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='geo.Coordinate2D.Error.longitude', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\232\246\035\t\t\000\000\000\000\000\000\000\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=442,
)

_COORDINATE2D = _descriptor.Descriptor(
  name='Coordinate2D',
  full_name='geo.Coordinate2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='geo.Coordinate2D.latitude', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\232\246\035\t\t\000\000\000\000\000\200V\300\242\246\035\t\t\000\000\000\000\000\200V@'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='geo.Coordinate2D.longitude', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\232\246\035\t\t\000\000\000\000\000\200f\300\242\246\035\t\t\000\000\000\000\000\200f@'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='geo.Coordinate2D.error', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\246\035\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COORDINATE2D_ERROR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=442,
)


_POSITION4D = _descriptor.Descriptor(
  name='Position4D',
  full_name='geo.Position4D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='geo.Position4D.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='geo.Position4D.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=554,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='geo.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='southwest', full_name='geo.BoundingBox.southwest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='northeast', full_name='geo.BoundingBox.northeast', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=645,
)


_LINEARRING = _descriptor.Descriptor(
  name='LinearRing',
  full_name='geo.LinearRing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='geo.LinearRing.coordinates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=699,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='geo.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rings', full_name='geo.Polygon.rings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=742,
)

_COORDINATE2D_ERROR.fields_by_name['latitude'].message_type = units_dot_units__pb2._DEGREES
_COORDINATE2D_ERROR.fields_by_name['longitude'].message_type = units_dot_units__pb2._DEGREES
_COORDINATE2D_ERROR.containing_type = _COORDINATE2D
_COORDINATE2D.fields_by_name['latitude'].message_type = units_dot_units__pb2._DEGREES
_COORDINATE2D.fields_by_name['longitude'].message_type = units_dot_units__pb2._DEGREES
_COORDINATE2D.fields_by_name['error'].message_type = _COORDINATE2D_ERROR
_POSITION4D.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_POSITION4D.fields_by_name['position'].message_type = measurements_dot_measurements__pb2._POSITION_ABSOLUTE
_BOUNDINGBOX.fields_by_name['southwest'].message_type = _COORDINATE2D
_BOUNDINGBOX.fields_by_name['northeast'].message_type = _COORDINATE2D
_LINEARRING.fields_by_name['coordinates'].message_type = _COORDINATE2D
_POLYGON.fields_by_name['rings'].message_type = _LINEARRING
DESCRIPTOR.message_types_by_name['Coordinate2D'] = _COORDINATE2D
DESCRIPTOR.message_types_by_name['Position4D'] = _POSITION4D
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['LinearRing'] = _LINEARRING
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinate2D = _reflection.GeneratedProtocolMessageType('Coordinate2D', (_message.Message,), dict(

  Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
    DESCRIPTOR = _COORDINATE2D_ERROR,
    __module__ = 'geo.geo_pb2'
    # @@protoc_insertion_point(class_scope:geo.Coordinate2D.Error)
    ))
  ,
  DESCRIPTOR = _COORDINATE2D,
  __module__ = 'geo.geo_pb2'
  # @@protoc_insertion_point(class_scope:geo.Coordinate2D)
  ))
_sym_db.RegisterMessage(Coordinate2D)
_sym_db.RegisterMessage(Coordinate2D.Error)

Position4D = _reflection.GeneratedProtocolMessageType('Position4D', (_message.Message,), dict(
  DESCRIPTOR = _POSITION4D,
  __module__ = 'geo.geo_pb2'
  # @@protoc_insertion_point(class_scope:geo.Position4D)
  ))
_sym_db.RegisterMessage(Position4D)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'geo.geo_pb2'
  # @@protoc_insertion_point(class_scope:geo.BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)

LinearRing = _reflection.GeneratedProtocolMessageType('LinearRing', (_message.Message,), dict(
  DESCRIPTOR = _LINEARRING,
  __module__ = 'geo.geo_pb2'
  # @@protoc_insertion_point(class_scope:geo.LinearRing)
  ))
_sym_db.RegisterMessage(LinearRing)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'geo.geo_pb2'
  # @@protoc_insertion_point(class_scope:geo.Polygon)
  ))
_sym_db.RegisterMessage(Polygon)


DESCRIPTOR._options = None
_COORDINATE2D_ERROR.fields_by_name['latitude']._options = None
_COORDINATE2D_ERROR.fields_by_name['longitude']._options = None
_COORDINATE2D.fields_by_name['latitude']._options = None
_COORDINATE2D.fields_by_name['longitude']._options = None
_COORDINATE2D.fields_by_name['error']._options = None
# @@protoc_insertion_point(module_scope)
