# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurements/dop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurements/dop.proto',
  package='measurements',
  syntax='proto3',
  serialized_options=_b('Z0github.com/airmap/interfaces/src/go/measurements'),
  serialized_pb=_b('\n\x16measurements/dop.proto\x12\x0cmeasurements\"=\n\x03\x44OP\x1a\x1b\n\nHorizontal\x12\r\n\x05value\x18\x01 \x01(\x01\x1a\x19\n\x08Vertical\x12\r\n\x05value\x18\x01 \x01(\x01\x42\x32Z0github.com/airmap/interfaces/src/go/measurementsb\x06proto3')
)




_DOP_HORIZONTAL = _descriptor.Descriptor(
  name='Horizontal',
  full_name='measurements.DOP.Horizontal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='measurements.DOP.Horizontal.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=74,
)

_DOP_VERTICAL = _descriptor.Descriptor(
  name='Vertical',
  full_name='measurements.DOP.Vertical',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='measurements.DOP.Vertical.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=101,
)

_DOP = _descriptor.Descriptor(
  name='DOP',
  full_name='measurements.DOP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_DOP_HORIZONTAL, _DOP_VERTICAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=101,
)

_DOP_HORIZONTAL.containing_type = _DOP
_DOP_VERTICAL.containing_type = _DOP
DESCRIPTOR.message_types_by_name['DOP'] = _DOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DOP = _reflection.GeneratedProtocolMessageType('DOP', (_message.Message,), dict(

  Horizontal = _reflection.GeneratedProtocolMessageType('Horizontal', (_message.Message,), dict(
    DESCRIPTOR = _DOP_HORIZONTAL,
    __module__ = 'measurements.dop_pb2'
    # @@protoc_insertion_point(class_scope:measurements.DOP.Horizontal)
    ))
  ,

  Vertical = _reflection.GeneratedProtocolMessageType('Vertical', (_message.Message,), dict(
    DESCRIPTOR = _DOP_VERTICAL,
    __module__ = 'measurements.dop_pb2'
    # @@protoc_insertion_point(class_scope:measurements.DOP.Vertical)
    ))
  ,
  DESCRIPTOR = _DOP,
  __module__ = 'measurements.dop_pb2'
  # @@protoc_insertion_point(class_scope:measurements.DOP)
  ))
_sym_db.RegisterMessage(DOP)
_sym_db.RegisterMessage(DOP.Horizontal)
_sym_db.RegisterMessage(DOP.Vertical)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
