// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry/report.proto

package telemetry

import (
	fmt "fmt"
	_ "github.com/airmap/interfaces/src/go"
	measurements "github.com/airmap/interfaces/src/go/measurements"
	tracking "github.com/airmap/interfaces/src/go/tracking"
	units "github.com/airmap/interfaces/src/go/units"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Band marks a radio frequency band.
type Report_Vehicle_System_Communication_Band int32

const (
	Report_Vehicle_System_Communication_BAND_UNKNOWN  Report_Vehicle_System_Communication_Band = 0
	Report_Vehicle_System_Communication_BAND_2DOT4GHZ Report_Vehicle_System_Communication_Band = 1
	Report_Vehicle_System_Communication_BAND_5DOT0GHZ Report_Vehicle_System_Communication_Band = 2
)

var Report_Vehicle_System_Communication_Band_name = map[int32]string{
	0: "BAND_UNKNOWN",
	1: "BAND_2DOT4GHZ",
	2: "BAND_5DOT0GHZ",
}

var Report_Vehicle_System_Communication_Band_value = map[string]int32{
	"BAND_UNKNOWN":  0,
	"BAND_2DOT4GHZ": 1,
	"BAND_5DOT0GHZ": 2,
}

func (x Report_Vehicle_System_Communication_Band) String() string {
	return proto.EnumName(Report_Vehicle_System_Communication_Band_name, int32(x))
}

func (Report_Vehicle_System_Communication_Band) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 2, 0}
}

// Report models a telemetry report at a given point in time.
type Report struct {
	Observed   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=observed,proto3" json:"observed,omitempty"`
	Identities []*tracking.Identity `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	// details is a discriminated union of all report types.
	//
	// Types that are valid to be assigned to Details:
	//	*Report_Spatial_
	//	*Report_Vehicle_
	//	*Report_Atmosphere_
	Details              isReport_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetObserved() *timestamp.Timestamp {
	if m != nil {
		return m.Observed
	}
	return nil
}

func (m *Report) GetIdentities() []*tracking.Identity {
	if m != nil {
		return m.Identities
	}
	return nil
}

type isReport_Details interface {
	isReport_Details()
}

type Report_Spatial_ struct {
	Spatial *Report_Spatial `protobuf:"bytes,3,opt,name=spatial,proto3,oneof"`
}

type Report_Vehicle_ struct {
	Vehicle *Report_Vehicle `protobuf:"bytes,4,opt,name=vehicle,proto3,oneof"`
}

type Report_Atmosphere_ struct {
	Atmosphere *Report_Atmosphere `protobuf:"bytes,5,opt,name=atmosphere,proto3,oneof"`
}

func (*Report_Spatial_) isReport_Details() {}

func (*Report_Vehicle_) isReport_Details() {}

func (*Report_Atmosphere_) isReport_Details() {}

func (m *Report) GetDetails() isReport_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Report) GetSpatial() *Report_Spatial {
	if x, ok := m.GetDetails().(*Report_Spatial_); ok {
		return x.Spatial
	}
	return nil
}

func (m *Report) GetVehicle() *Report_Vehicle {
	if x, ok := m.GetDetails().(*Report_Vehicle_); ok {
		return x.Vehicle
	}
	return nil
}

func (m *Report) GetAtmosphere() *Report_Atmosphere {
	if x, ok := m.GetDetails().(*Report_Atmosphere_); ok {
		return x.Atmosphere
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Report) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Report_Spatial_)(nil),
		(*Report_Vehicle_)(nil),
		(*Report_Atmosphere_)(nil),
	}
}

// Spatial models a spatial report
type Report_Spatial struct {
	Position             *measurements.Position     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *measurements.Velocity     `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Orientation          *measurements.Orientation  `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Acceleration         *measurements.Acceleration `protobuf:"bytes,4,opt,name=acceleration,proto3" json:"acceleration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Report_Spatial) Reset()         { *m = Report_Spatial{} }
func (m *Report_Spatial) String() string { return proto.CompactTextString(m) }
func (*Report_Spatial) ProtoMessage()    {}
func (*Report_Spatial) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 0}
}

func (m *Report_Spatial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Spatial.Unmarshal(m, b)
}
func (m *Report_Spatial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Spatial.Marshal(b, m, deterministic)
}
func (m *Report_Spatial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Spatial.Merge(m, src)
}
func (m *Report_Spatial) XXX_Size() int {
	return xxx_messageInfo_Report_Spatial.Size(m)
}
func (m *Report_Spatial) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Spatial.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Spatial proto.InternalMessageInfo

func (m *Report_Spatial) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Report_Spatial) GetVelocity() *measurements.Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Report_Spatial) GetOrientation() *measurements.Orientation {
	if m != nil {
		return m.Orientation
	}
	return nil
}

func (m *Report_Spatial) GetAcceleration() *measurements.Acceleration {
	if m != nil {
		return m.Acceleration
	}
	return nil
}

// Vehicle models a vehicle report
type Report_Vehicle struct {
	Systems              []*Report_Vehicle_System  `protobuf:"bytes,1,rep,name=systems,proto3" json:"systems,omitempty"`
	Endurance            *Report_Vehicle_Endurance `protobuf:"bytes,2,opt,name=endurance,proto3" json:"endurance,omitempty"`
	Airborne             *wrappers.BoolValue       `protobuf:"bytes,3,opt,name=airborne,proto3" json:"airborne,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Report_Vehicle) Reset()         { *m = Report_Vehicle{} }
func (m *Report_Vehicle) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle) ProtoMessage()    {}
func (*Report_Vehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1}
}

func (m *Report_Vehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle.Unmarshal(m, b)
}
func (m *Report_Vehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle.Merge(m, src)
}
func (m *Report_Vehicle) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle.Size(m)
}
func (m *Report_Vehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle proto.InternalMessageInfo

func (m *Report_Vehicle) GetSystems() []*Report_Vehicle_System {
	if m != nil {
		return m.Systems
	}
	return nil
}

func (m *Report_Vehicle) GetEndurance() *Report_Vehicle_Endurance {
	if m != nil {
		return m.Endurance
	}
	return nil
}

func (m *Report_Vehicle) GetAirborne() *wrappers.BoolValue {
	if m != nil {
		return m.Airborne
	}
	return nil
}

// System models a discrete vehicle system.
type Report_Vehicle_System struct {
	// Types that are valid to be assigned to Details:
	//	*Report_Vehicle_System_Electrical_
	//	*Report_Vehicle_System_Communication_
	//	*Report_Vehicle_System_Propulsion_
	//	*Report_Vehicle_System_Safety_
	Details              isReport_Vehicle_System_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Report_Vehicle_System) Reset()         { *m = Report_Vehicle_System{} }
func (m *Report_Vehicle_System) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System) ProtoMessage()    {}
func (*Report_Vehicle_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0}
}

func (m *Report_Vehicle_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System.Unmarshal(m, b)
}
func (m *Report_Vehicle_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System.Merge(m, src)
}
func (m *Report_Vehicle_System) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System.Size(m)
}
func (m *Report_Vehicle_System) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System proto.InternalMessageInfo

type isReport_Vehicle_System_Details interface {
	isReport_Vehicle_System_Details()
}

type Report_Vehicle_System_Electrical_ struct {
	Electrical *Report_Vehicle_System_Electrical `protobuf:"bytes,1,opt,name=electrical,proto3,oneof"`
}

type Report_Vehicle_System_Communication_ struct {
	Communication *Report_Vehicle_System_Communication `protobuf:"bytes,2,opt,name=communication,proto3,oneof"`
}

type Report_Vehicle_System_Propulsion_ struct {
	Propulsion *Report_Vehicle_System_Propulsion `protobuf:"bytes,3,opt,name=propulsion,proto3,oneof"`
}

type Report_Vehicle_System_Safety_ struct {
	Safety *Report_Vehicle_System_Safety `protobuf:"bytes,4,opt,name=safety,proto3,oneof"`
}

func (*Report_Vehicle_System_Electrical_) isReport_Vehicle_System_Details() {}

func (*Report_Vehicle_System_Communication_) isReport_Vehicle_System_Details() {}

func (*Report_Vehicle_System_Propulsion_) isReport_Vehicle_System_Details() {}

func (*Report_Vehicle_System_Safety_) isReport_Vehicle_System_Details() {}

func (m *Report_Vehicle_System) GetDetails() isReport_Vehicle_System_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Report_Vehicle_System) GetElectrical() *Report_Vehicle_System_Electrical {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Electrical_); ok {
		return x.Electrical
	}
	return nil
}

func (m *Report_Vehicle_System) GetCommunication() *Report_Vehicle_System_Communication {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Communication_); ok {
		return x.Communication
	}
	return nil
}

func (m *Report_Vehicle_System) GetPropulsion() *Report_Vehicle_System_Propulsion {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Propulsion_); ok {
		return x.Propulsion
	}
	return nil
}

func (m *Report_Vehicle_System) GetSafety() *Report_Vehicle_System_Safety {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Safety_); ok {
		return x.Safety
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Report_Vehicle_System) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Report_Vehicle_System_Electrical_)(nil),
		(*Report_Vehicle_System_Communication_)(nil),
		(*Report_Vehicle_System_Propulsion_)(nil),
		(*Report_Vehicle_System_Safety_)(nil),
	}
}

// Electrical models the electrical system.
type Report_Vehicle_System_Electrical struct {
	Buses                []*Report_Vehicle_System_Electrical_Bus     `protobuf:"bytes,1,rep,name=buses,proto3" json:"buses,omitempty"`
	Batteries            []*Report_Vehicle_System_Electrical_Battery `protobuf:"bytes,2,rep,name=batteries,proto3" json:"batteries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Report_Vehicle_System_Electrical) Reset()         { *m = Report_Vehicle_System_Electrical{} }
func (m *Report_Vehicle_System_Electrical) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Electrical) ProtoMessage()    {}
func (*Report_Vehicle_System_Electrical) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 0}
}

func (m *Report_Vehicle_System_Electrical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Electrical.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Electrical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Electrical.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Electrical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Electrical.Merge(m, src)
}
func (m *Report_Vehicle_System_Electrical) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Electrical.Size(m)
}
func (m *Report_Vehicle_System_Electrical) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Electrical.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Electrical proto.InternalMessageInfo

func (m *Report_Vehicle_System_Electrical) GetBuses() []*Report_Vehicle_System_Electrical_Bus {
	if m != nil {
		return m.Buses
	}
	return nil
}

func (m *Report_Vehicle_System_Electrical) GetBatteries() []*Report_Vehicle_System_Electrical_Battery {
	if m != nil {
		return m.Batteries
	}
	return nil
}

// Bus models an electrical bus.
type Report_Vehicle_System_Electrical_Bus struct {
	Number               uint32         `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Voltage              *units.Volts   `protobuf:"bytes,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current              *units.Amperes `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Report_Vehicle_System_Electrical_Bus) Reset()         { *m = Report_Vehicle_System_Electrical_Bus{} }
func (m *Report_Vehicle_System_Electrical_Bus) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Electrical_Bus) ProtoMessage()    {}
func (*Report_Vehicle_System_Electrical_Bus) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 0, 0}
}

func (m *Report_Vehicle_System_Electrical_Bus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Electrical_Bus.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Electrical_Bus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Electrical_Bus.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Electrical_Bus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Electrical_Bus.Merge(m, src)
}
func (m *Report_Vehicle_System_Electrical_Bus) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Electrical_Bus.Size(m)
}
func (m *Report_Vehicle_System_Electrical_Bus) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Electrical_Bus.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Electrical_Bus proto.InternalMessageInfo

func (m *Report_Vehicle_System_Electrical_Bus) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Report_Vehicle_System_Electrical_Bus) GetVoltage() *units.Volts {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *Report_Vehicle_System_Electrical_Bus) GetCurrent() *units.Amperes {
	if m != nil {
		return m.Current
	}
	return nil
}

// Battery models a battery.
type Report_Vehicle_System_Electrical_Battery struct {
	Number               uint32             `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Temperature          *units.Celsius     `protobuf:"bytes,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Voltage              *units.Volts       `protobuf:"bytes,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current              *units.Amperes     `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	Capacity             *units.AmpereHours `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Charge               *units.Percent     `protobuf:"bytes,6,opt,name=charge,proto3" json:"charge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Report_Vehicle_System_Electrical_Battery) Reset() {
	*m = Report_Vehicle_System_Electrical_Battery{}
}
func (m *Report_Vehicle_System_Electrical_Battery) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Electrical_Battery) ProtoMessage()    {}
func (*Report_Vehicle_System_Electrical_Battery) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 0, 1}
}

func (m *Report_Vehicle_System_Electrical_Battery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Electrical_Battery.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Electrical_Battery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Electrical_Battery.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Electrical_Battery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Electrical_Battery.Merge(m, src)
}
func (m *Report_Vehicle_System_Electrical_Battery) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Electrical_Battery.Size(m)
}
func (m *Report_Vehicle_System_Electrical_Battery) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Electrical_Battery.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Electrical_Battery proto.InternalMessageInfo

func (m *Report_Vehicle_System_Electrical_Battery) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Report_Vehicle_System_Electrical_Battery) GetTemperature() *units.Celsius {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Report_Vehicle_System_Electrical_Battery) GetVoltage() *units.Volts {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *Report_Vehicle_System_Electrical_Battery) GetCurrent() *units.Amperes {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *Report_Vehicle_System_Electrical_Battery) GetCapacity() *units.AmpereHours {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *Report_Vehicle_System_Electrical_Battery) GetCharge() *units.Percent {
	if m != nil {
		return m.Charge
	}
	return nil
}

// Propulsion models the propulsion system.
type Report_Vehicle_System_Propulsion struct {
	Motors               []*Report_Vehicle_System_Propulsion_Motor `protobuf:"bytes,1,rep,name=motors,proto3" json:"motors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Report_Vehicle_System_Propulsion) Reset()         { *m = Report_Vehicle_System_Propulsion{} }
func (m *Report_Vehicle_System_Propulsion) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Propulsion) ProtoMessage()    {}
func (*Report_Vehicle_System_Propulsion) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 1}
}

func (m *Report_Vehicle_System_Propulsion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Propulsion.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Propulsion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Propulsion.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Propulsion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Propulsion.Merge(m, src)
}
func (m *Report_Vehicle_System_Propulsion) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Propulsion.Size(m)
}
func (m *Report_Vehicle_System_Propulsion) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Propulsion.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Propulsion proto.InternalMessageInfo

func (m *Report_Vehicle_System_Propulsion) GetMotors() []*Report_Vehicle_System_Propulsion_Motor {
	if m != nil {
		return m.Motors
	}
	return nil
}

type Report_Vehicle_System_Propulsion_Motor struct {
	Number               uint32         `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Voltage              *units.Volts   `protobuf:"bytes,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current              *units.Amperes `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	Temperature          *units.Celsius `protobuf:"bytes,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Rpm                  *units.RPM     `protobuf:"bytes,5,opt,name=rpm,proto3" json:"rpm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Report_Vehicle_System_Propulsion_Motor) Reset() {
	*m = Report_Vehicle_System_Propulsion_Motor{}
}
func (m *Report_Vehicle_System_Propulsion_Motor) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Propulsion_Motor) ProtoMessage()    {}
func (*Report_Vehicle_System_Propulsion_Motor) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 1, 0}
}

func (m *Report_Vehicle_System_Propulsion_Motor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Propulsion_Motor.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Propulsion_Motor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Propulsion_Motor.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Propulsion_Motor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Propulsion_Motor.Merge(m, src)
}
func (m *Report_Vehicle_System_Propulsion_Motor) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Propulsion_Motor.Size(m)
}
func (m *Report_Vehicle_System_Propulsion_Motor) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Propulsion_Motor.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Propulsion_Motor proto.InternalMessageInfo

func (m *Report_Vehicle_System_Propulsion_Motor) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Report_Vehicle_System_Propulsion_Motor) GetVoltage() *units.Volts {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *Report_Vehicle_System_Propulsion_Motor) GetCurrent() *units.Amperes {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *Report_Vehicle_System_Propulsion_Motor) GetTemperature() *units.Celsius {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Report_Vehicle_System_Propulsion_Motor) GetRpm() *units.RPM {
	if m != nil {
		return m.Rpm
	}
	return nil
}

// Communication models the communication system.
type Report_Vehicle_System_Communication struct {
	Links                []*Report_Vehicle_System_Communication_Link `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Report_Vehicle_System_Communication) Reset()         { *m = Report_Vehicle_System_Communication{} }
func (m *Report_Vehicle_System_Communication) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Communication) ProtoMessage()    {}
func (*Report_Vehicle_System_Communication) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 2}
}

func (m *Report_Vehicle_System_Communication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Communication.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Communication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Communication.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Communication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Communication.Merge(m, src)
}
func (m *Report_Vehicle_System_Communication) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Communication.Size(m)
}
func (m *Report_Vehicle_System_Communication) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Communication.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Communication proto.InternalMessageInfo

func (m *Report_Vehicle_System_Communication) GetLinks() []*Report_Vehicle_System_Communication_Link {
	if m != nil {
		return m.Links
	}
	return nil
}

// Link models a communication link.
type Report_Vehicle_System_Communication_Link struct {
	// Types that are valid to be assigned to Details:
	//	*Report_Vehicle_System_Communication_Link_Gps
	//	*Report_Vehicle_System_Communication_Link_Wifi
	//	*Report_Vehicle_System_Communication_Link_Cellular_
	Details              isReport_Vehicle_System_Communication_Link_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Report_Vehicle_System_Communication_Link) Reset() {
	*m = Report_Vehicle_System_Communication_Link{}
}
func (m *Report_Vehicle_System_Communication_Link) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Communication_Link) ProtoMessage()    {}
func (*Report_Vehicle_System_Communication_Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 2, 0}
}

func (m *Report_Vehicle_System_Communication_Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Communication_Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Communication_Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link.Merge(m, src)
}
func (m *Report_Vehicle_System_Communication_Link) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link.Size(m)
}
func (m *Report_Vehicle_System_Communication_Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Communication_Link proto.InternalMessageInfo

type isReport_Vehicle_System_Communication_Link_Details interface {
	isReport_Vehicle_System_Communication_Link_Details()
}

type Report_Vehicle_System_Communication_Link_Gps struct {
	Gps *Report_Vehicle_System_Communication_Link_GPS `protobuf:"bytes,1,opt,name=gps,proto3,oneof"`
}

type Report_Vehicle_System_Communication_Link_Wifi struct {
	Wifi *Report_Vehicle_System_Communication_Link_WiFi `protobuf:"bytes,2,opt,name=wifi,proto3,oneof"`
}

type Report_Vehicle_System_Communication_Link_Cellular_ struct {
	Cellular *Report_Vehicle_System_Communication_Link_Cellular `protobuf:"bytes,3,opt,name=cellular,proto3,oneof"`
}

func (*Report_Vehicle_System_Communication_Link_Gps) isReport_Vehicle_System_Communication_Link_Details() {
}

func (*Report_Vehicle_System_Communication_Link_Wifi) isReport_Vehicle_System_Communication_Link_Details() {
}

func (*Report_Vehicle_System_Communication_Link_Cellular_) isReport_Vehicle_System_Communication_Link_Details() {
}

func (m *Report_Vehicle_System_Communication_Link) GetDetails() isReport_Vehicle_System_Communication_Link_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Report_Vehicle_System_Communication_Link) GetGps() *Report_Vehicle_System_Communication_Link_GPS {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Communication_Link_Gps); ok {
		return x.Gps
	}
	return nil
}

func (m *Report_Vehicle_System_Communication_Link) GetWifi() *Report_Vehicle_System_Communication_Link_WiFi {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Communication_Link_Wifi); ok {
		return x.Wifi
	}
	return nil
}

func (m *Report_Vehicle_System_Communication_Link) GetCellular() *Report_Vehicle_System_Communication_Link_Cellular {
	if x, ok := m.GetDetails().(*Report_Vehicle_System_Communication_Link_Cellular_); ok {
		return x.Cellular
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Report_Vehicle_System_Communication_Link) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Report_Vehicle_System_Communication_Link_Gps)(nil),
		(*Report_Vehicle_System_Communication_Link_Wifi)(nil),
		(*Report_Vehicle_System_Communication_Link_Cellular_)(nil),
	}
}

// WiFi models a Wi-Fi link.
type Report_Vehicle_System_Communication_Link_WiFi struct {
	Number               uint32                                   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Ssid                 string                                   `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Channel              uint32                                   `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Band                 Report_Vehicle_System_Communication_Band `protobuf:"varint,4,opt,name=band,proto3,enum=telemetry.Report_Vehicle_System_Communication_Band" json:"band,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *Report_Vehicle_System_Communication_Link_WiFi) Reset() {
	*m = Report_Vehicle_System_Communication_Link_WiFi{}
}
func (m *Report_Vehicle_System_Communication_Link_WiFi) String() string {
	return proto.CompactTextString(m)
}
func (*Report_Vehicle_System_Communication_Link_WiFi) ProtoMessage() {}
func (*Report_Vehicle_System_Communication_Link_WiFi) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 2, 0, 0}
}

func (m *Report_Vehicle_System_Communication_Link_WiFi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_WiFi.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Communication_Link_WiFi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_WiFi.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Communication_Link_WiFi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link_WiFi.Merge(m, src)
}
func (m *Report_Vehicle_System_Communication_Link_WiFi) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_WiFi.Size(m)
}
func (m *Report_Vehicle_System_Communication_Link_WiFi) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link_WiFi.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Communication_Link_WiFi proto.InternalMessageInfo

func (m *Report_Vehicle_System_Communication_Link_WiFi) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Report_Vehicle_System_Communication_Link_WiFi) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *Report_Vehicle_System_Communication_Link_WiFi) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *Report_Vehicle_System_Communication_Link_WiFi) GetBand() Report_Vehicle_System_Communication_Band {
	if m != nil {
		return m.Band
	}
	return Report_Vehicle_System_Communication_BAND_UNKNOWN
}

// GPS models a Global Positioning System link.
type Report_Vehicle_System_Communication_Link_GPS struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Satellites           uint32   `protobuf:"varint,2,opt,name=satellites,proto3" json:"satellites,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report_Vehicle_System_Communication_Link_GPS) Reset() {
	*m = Report_Vehicle_System_Communication_Link_GPS{}
}
func (m *Report_Vehicle_System_Communication_Link_GPS) String() string {
	return proto.CompactTextString(m)
}
func (*Report_Vehicle_System_Communication_Link_GPS) ProtoMessage() {}
func (*Report_Vehicle_System_Communication_Link_GPS) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 2, 0, 1}
}

func (m *Report_Vehicle_System_Communication_Link_GPS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_GPS.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Communication_Link_GPS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_GPS.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Communication_Link_GPS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link_GPS.Merge(m, src)
}
func (m *Report_Vehicle_System_Communication_Link_GPS) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_GPS.Size(m)
}
func (m *Report_Vehicle_System_Communication_Link_GPS) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link_GPS.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Communication_Link_GPS proto.InternalMessageInfo

func (m *Report_Vehicle_System_Communication_Link_GPS) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Report_Vehicle_System_Communication_Link_GPS) GetSatellites() uint32 {
	if m != nil {
		return m.Satellites
	}
	return 0
}

// Cellular models a cellular telecom link.
type Report_Vehicle_System_Communication_Link_Cellular struct {
	Number               uint32          `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Signal               *units.Decibels `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Report_Vehicle_System_Communication_Link_Cellular) Reset() {
	*m = Report_Vehicle_System_Communication_Link_Cellular{}
}
func (m *Report_Vehicle_System_Communication_Link_Cellular) String() string {
	return proto.CompactTextString(m)
}
func (*Report_Vehicle_System_Communication_Link_Cellular) ProtoMessage() {}
func (*Report_Vehicle_System_Communication_Link_Cellular) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 2, 0, 2}
}

func (m *Report_Vehicle_System_Communication_Link_Cellular) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_Cellular.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Communication_Link_Cellular) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_Cellular.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Communication_Link_Cellular) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link_Cellular.Merge(m, src)
}
func (m *Report_Vehicle_System_Communication_Link_Cellular) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Communication_Link_Cellular.Size(m)
}
func (m *Report_Vehicle_System_Communication_Link_Cellular) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Communication_Link_Cellular.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Communication_Link_Cellular proto.InternalMessageInfo

func (m *Report_Vehicle_System_Communication_Link_Cellular) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Report_Vehicle_System_Communication_Link_Cellular) GetSignal() *units.Decibels {
	if m != nil {
		return m.Signal
	}
	return nil
}

// Safety models the safety system.
type Report_Vehicle_System_Safety struct {
	LossOfLink           *wrappers.BoolValue `protobuf:"bytes,1,opt,name=loss_of_link,json=lossOfLink,proto3" json:"loss_of_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Report_Vehicle_System_Safety) Reset()         { *m = Report_Vehicle_System_Safety{} }
func (m *Report_Vehicle_System_Safety) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_System_Safety) ProtoMessage()    {}
func (*Report_Vehicle_System_Safety) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 0, 3}
}

func (m *Report_Vehicle_System_Safety) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_System_Safety.Unmarshal(m, b)
}
func (m *Report_Vehicle_System_Safety) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_System_Safety.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_System_Safety) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_System_Safety.Merge(m, src)
}
func (m *Report_Vehicle_System_Safety) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_System_Safety.Size(m)
}
func (m *Report_Vehicle_System_Safety) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_System_Safety.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_System_Safety proto.InternalMessageInfo

func (m *Report_Vehicle_System_Safety) GetLossOfLink() *wrappers.BoolValue {
	if m != nil {
		return m.LossOfLink
	}
	return nil
}

// Endurance models the run endurance of a vehicle.
type Report_Vehicle_Endurance struct {
	Duration             *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Distance             *units.Meters      `protobuf:"bytes,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Report_Vehicle_Endurance) Reset()         { *m = Report_Vehicle_Endurance{} }
func (m *Report_Vehicle_Endurance) String() string { return proto.CompactTextString(m) }
func (*Report_Vehicle_Endurance) ProtoMessage()    {}
func (*Report_Vehicle_Endurance) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1, 1}
}

func (m *Report_Vehicle_Endurance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Vehicle_Endurance.Unmarshal(m, b)
}
func (m *Report_Vehicle_Endurance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Vehicle_Endurance.Marshal(b, m, deterministic)
}
func (m *Report_Vehicle_Endurance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Vehicle_Endurance.Merge(m, src)
}
func (m *Report_Vehicle_Endurance) XXX_Size() int {
	return xxx_messageInfo_Report_Vehicle_Endurance.Size(m)
}
func (m *Report_Vehicle_Endurance) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Vehicle_Endurance.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Vehicle_Endurance proto.InternalMessageInfo

func (m *Report_Vehicle_Endurance) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Report_Vehicle_Endurance) GetDistance() *units.Meters {
	if m != nil {
		return m.Distance
	}
	return nil
}

// Atmosphere models an atmospheric report
type Report_Atmosphere struct {
	Position             *measurements.Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Pressure             *units.Pascals         `protobuf:"bytes,2,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Temperature          *units.Celsius         `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Wind                 *units.MetersPerSecond `protobuf:"bytes,4,opt,name=wind,proto3" json:"wind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Report_Atmosphere) Reset()         { *m = Report_Atmosphere{} }
func (m *Report_Atmosphere) String() string { return proto.CompactTextString(m) }
func (*Report_Atmosphere) ProtoMessage()    {}
func (*Report_Atmosphere) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 2}
}

func (m *Report_Atmosphere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Atmosphere.Unmarshal(m, b)
}
func (m *Report_Atmosphere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Atmosphere.Marshal(b, m, deterministic)
}
func (m *Report_Atmosphere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Atmosphere.Merge(m, src)
}
func (m *Report_Atmosphere) XXX_Size() int {
	return xxx_messageInfo_Report_Atmosphere.Size(m)
}
func (m *Report_Atmosphere) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Atmosphere.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Atmosphere proto.InternalMessageInfo

func (m *Report_Atmosphere) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Report_Atmosphere) GetPressure() *units.Pascals {
	if m != nil {
		return m.Pressure
	}
	return nil
}

func (m *Report_Atmosphere) GetTemperature() *units.Celsius {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Report_Atmosphere) GetWind() *units.MetersPerSecond {
	if m != nil {
		return m.Wind
	}
	return nil
}

func init() {
	proto.RegisterEnum("telemetry.Report_Vehicle_System_Communication_Band", Report_Vehicle_System_Communication_Band_name, Report_Vehicle_System_Communication_Band_value)
	proto.RegisterType((*Report)(nil), "telemetry.Report")
	proto.RegisterType((*Report_Spatial)(nil), "telemetry.Report.Spatial")
	proto.RegisterType((*Report_Vehicle)(nil), "telemetry.Report.Vehicle")
	proto.RegisterType((*Report_Vehicle_System)(nil), "telemetry.Report.Vehicle.System")
	proto.RegisterType((*Report_Vehicle_System_Electrical)(nil), "telemetry.Report.Vehicle.System.Electrical")
	proto.RegisterType((*Report_Vehicle_System_Electrical_Bus)(nil), "telemetry.Report.Vehicle.System.Electrical.Bus")
	proto.RegisterType((*Report_Vehicle_System_Electrical_Battery)(nil), "telemetry.Report.Vehicle.System.Electrical.Battery")
	proto.RegisterType((*Report_Vehicle_System_Propulsion)(nil), "telemetry.Report.Vehicle.System.Propulsion")
	proto.RegisterType((*Report_Vehicle_System_Propulsion_Motor)(nil), "telemetry.Report.Vehicle.System.Propulsion.Motor")
	proto.RegisterType((*Report_Vehicle_System_Communication)(nil), "telemetry.Report.Vehicle.System.Communication")
	proto.RegisterType((*Report_Vehicle_System_Communication_Link)(nil), "telemetry.Report.Vehicle.System.Communication.Link")
	proto.RegisterType((*Report_Vehicle_System_Communication_Link_WiFi)(nil), "telemetry.Report.Vehicle.System.Communication.Link.WiFi")
	proto.RegisterType((*Report_Vehicle_System_Communication_Link_GPS)(nil), "telemetry.Report.Vehicle.System.Communication.Link.GPS")
	proto.RegisterType((*Report_Vehicle_System_Communication_Link_Cellular)(nil), "telemetry.Report.Vehicle.System.Communication.Link.Cellular")
	proto.RegisterType((*Report_Vehicle_System_Safety)(nil), "telemetry.Report.Vehicle.System.Safety")
	proto.RegisterType((*Report_Vehicle_Endurance)(nil), "telemetry.Report.Vehicle.Endurance")
	proto.RegisterType((*Report_Atmosphere)(nil), "telemetry.Report.Atmosphere")
}

func init() { proto.RegisterFile("telemetry/report.proto", fileDescriptor_822b117a32fda6fc) }

var fileDescriptor_822b117a32fda6fc = []byte{
	// 1233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcf, 0x6f, 0xdb, 0x36,
	0x14, 0xb6, 0x63, 0xc5, 0x76, 0x5e, 0x92, 0x2e, 0xe5, 0xa1, 0x73, 0x85, 0xae, 0x2d, 0xba, 0x01,
	0x2b, 0xb0, 0x56, 0xea, 0xd2, 0x1f, 0x2b, 0xb6, 0xa2, 0x40, 0xdc, 0x74, 0x71, 0xd0, 0x26, 0x31,
	0x94, 0x2e, 0x01, 0x7a, 0x29, 0x68, 0xf9, 0xc5, 0x21, 0x4a, 0x89, 0x02, 0x49, 0xa5, 0xcb, 0xad,
	0x3b, 0xed, 0xef, 0xd8, 0x65, 0x97, 0x61, 0xa7, 0xfd, 0x35, 0x1b, 0x86, 0xfd, 0x17, 0x3b, 0xed,
	0x32, 0x48, 0x22, 0x25, 0x39, 0x59, 0xe0, 0x26, 0x87, 0x5d, 0x0c, 0xf8, 0xf1, 0xfb, 0x3e, 0x3e,
	0x7e, 0xef, 0xf1, 0x89, 0x70, 0x45, 0x23, 0xc7, 0x08, 0xb5, 0x3c, 0xf6, 0x25, 0x26, 0x42, 0x6a,
	0x2f, 0x91, 0x42, 0x0b, 0xb2, 0x50, 0xc6, 0xdd, 0x1b, 0x13, 0x21, 0x26, 0x1c, 0xfd, 0x7c, 0x61,
	0x94, 0x1e, 0xf8, 0x9a, 0x45, 0xa8, 0x34, 0x8d, 0x92, 0x02, 0xeb, 0x5e, 0x3f, 0x09, 0x18, 0xa7,
	0x92, 0x6a, 0x26, 0xe2, 0xb3, 0xd6, 0xdf, 0x49, 0x9a, 0x24, 0x28, 0x95, 0x59, 0x5f, 0xc1, 0xef,
	0x35, 0xc6, 0x8a, 0x89, 0xd8, 0x46, 0x2e, 0xa7, 0x31, 0xd3, 0xca, 0xcf, 0x7f, 0x4d, 0xe8, 0x46,
	0x84, 0x54, 0xa5, 0x12, 0x23, 0x8c, 0xb5, 0xf2, 0xeb, 0x7f, 0x0c, 0xe0, 0x63, 0x2d, 0x69, 0xf8,
	0x96, 0xc5, 0x13, 0x9f, 0x8d, 0x31, 0xd6, 0x4c, 0x1f, 0x17, 0x0b, 0xb7, 0x7e, 0xbc, 0x0a, 0xed,
	0x20, 0x3f, 0x1b, 0x79, 0x04, 0x5d, 0x31, 0x52, 0x28, 0x8f, 0x70, 0xdc, 0x6b, 0xde, 0x6c, 0xde,
	0x5e, 0x5c, 0x75, 0xbd, 0x22, 0x39, 0xcf, 0x26, 0xe7, 0xbd, 0xb2, 0xa7, 0x0b, 0x4a, 0x2c, 0x59,
	0x05, 0x30, 0xa2, 0x0c, 0x55, 0x6f, 0xee, 0x66, 0xeb, 0xf6, 0xe2, 0x2a, 0xf1, 0xec, 0x86, 0xde,
	0xa6, 0xd9, 0x30, 0xa8, 0xa1, 0xc8, 0x43, 0xe8, 0xa8, 0x84, 0x6a, 0x46, 0x79, 0xaf, 0x95, 0x6f,
	0x75, 0xd5, 0x2b, 0x3d, 0xf5, 0x8a, 0x7c, 0xbc, 0xdd, 0x02, 0x30, 0x68, 0x04, 0x16, 0x9b, 0xd1,
	0x8e, 0xf0, 0x90, 0x85, 0x1c, 0x7b, 0xce, 0x59, 0xb4, 0xbd, 0x02, 0x90, 0xd1, 0x0c, 0x96, 0x3c,
	0x05, 0xa0, 0x3a, 0x12, 0x2a, 0x39, 0x44, 0x89, 0xbd, 0xf9, 0x9c, 0x79, 0xed, 0x34, 0x73, 0xad,
	0xc4, 0x0c, 0x1a, 0x41, 0x8d, 0xe1, 0xbe, 0x9f, 0x83, 0x8e, 0xc9, 0x86, 0xac, 0x42, 0x37, 0x11,
	0x8a, 0x65, 0x15, 0x34, 0x2e, 0x5d, 0xf1, 0xa6, 0x0c, 0x1f, 0x9a, 0xd5, 0xa0, 0xc4, 0x91, 0xc7,
	0xd0, 0x3d, 0x42, 0x2e, 0x42, 0xa6, 0x8f, 0x7b, 0x73, 0xff, 0xc5, 0xd9, 0x33, 0xab, 0x7d, 0xe7,
	0xfd, 0xcf, 0x9f, 0x34, 0x83, 0x12, 0x4d, 0xd6, 0x60, 0x51, 0x48, 0x86, 0xb1, 0xce, 0x5b, 0xa6,
	0xf4, 0x6a, 0x8a, 0xbc, 0x53, 0x01, 0x0c, 0xbf, 0xce, 0x21, 0xeb, 0xb0, 0x44, 0xc3, 0x10, 0x39,
	0x16, 0x6d, 0x67, 0x8c, 0x73, 0xa7, 0x35, 0xd6, 0x6a, 0x08, 0x23, 0x32, 0xc5, 0x72, 0xff, 0x26,
	0xd0, 0x31, 0xce, 0x92, 0xaf, 0xa1, 0xa3, 0x8e, 0x95, 0xc6, 0x48, 0xf5, 0x9a, 0x79, 0xb5, 0x6f,
	0x9e, 0x59, 0x05, 0x6f, 0x37, 0x07, 0x06, 0x96, 0x40, 0x36, 0x60, 0x01, 0xe3, 0xec, 0x0a, 0xc4,
	0x21, 0x1a, 0x2f, 0x3e, 0x3d, 0x9b, 0xfd, 0xdc, 0x42, 0x4d, 0x4e, 0x15, 0x97, 0x3c, 0x81, 0x2e,
	0x65, 0x72, 0x24, 0x64, 0x8c, 0xc6, 0x96, 0xd3, 0xdd, 0xda, 0x17, 0x82, 0xef, 0x51, 0x9e, 0x5a,
	0x7a, 0xc9, 0x70, 0x7f, 0x59, 0x81, 0x76, 0x91, 0x1a, 0xd9, 0x02, 0x40, 0x8e, 0xa1, 0x96, 0x2c,
	0xa4, 0xdc, 0x94, 0xf4, 0x8b, 0x59, 0x07, 0xf2, 0x9e, 0x97, 0x94, 0xac, 0x57, 0x2a, 0x01, 0xb2,
	0x07, 0xcb, 0xa1, 0x88, 0xa2, 0x34, 0x66, 0x61, 0xe1, 0x77, 0x71, 0x48, 0x6f, 0xa6, 0xe2, 0xb3,
	0x3a, 0x6b, 0xd0, 0x08, 0xa6, 0x65, 0xb2, 0x34, 0x13, 0x29, 0x92, 0x94, 0xab, 0xaa, 0x11, 0x66,
	0xa7, 0x39, 0x2c, 0x29, 0x59, 0x9a, 0x95, 0x00, 0x59, 0x83, 0xb6, 0xa2, 0x07, 0xa8, 0x8f, 0x4d,
	0x3f, 0x7c, 0x3e, 0x53, 0x6a, 0x37, 0x87, 0x0f, 0x1a, 0x81, 0x21, 0xba, 0x7f, 0x38, 0x00, 0x95,
	0x0d, 0xe4, 0x05, 0xcc, 0x8f, 0x52, 0x85, 0xb6, 0x27, 0xfc, 0x73, 0x58, 0xe8, 0xf5, 0x53, 0x65,
	0x4a, 0x54, 0x68, 0x90, 0x7d, 0x58, 0x18, 0x51, 0xad, 0x51, 0x56, 0x23, 0xe5, 0xfe, 0xb9, 0x04,
	0x73, 0xb2, 0xbd, 0x4f, 0x95, 0x96, 0xfb, 0x43, 0x13, 0x5a, 0xfd, 0x54, 0x91, 0x6b, 0xd0, 0x8e,
	0xd3, 0x68, 0x84, 0x32, 0xaf, 0xf8, 0xb2, 0x01, 0x9a, 0x18, 0xb9, 0x03, 0x9d, 0x23, 0xc1, 0x35,
	0x9d, 0xd8, 0x1e, 0x5d, 0xf2, 0x8a, 0x71, 0xbb, 0x27, 0xb8, 0xb6, 0xa9, 0x5a, 0x08, 0xf1, 0xa0,
	0x13, 0xa6, 0x52, 0x62, 0xac, 0x4d, 0x5d, 0x2e, 0x19, 0xf4, 0x5a, 0x94, 0xa0, 0xc4, 0x12, 0x6f,
	0x40, 0xee, 0x4f, 0x73, 0xd0, 0x31, 0x09, 0xce, 0xc8, 0xe3, 0x11, 0x2c, 0x6a, 0xcc, 0x44, 0xa8,
	0x4e, 0xa5, 0xcd, 0xc5, 0xaa, 0x3f, 0x43, 0xae, 0x58, 0x69, 0x5c, 0x1d, 0x58, 0xcf, 0xbf, 0x75,
	0xae, 0xfc, 0x9d, 0x0f, 0xc8, 0x9f, 0x3c, 0x80, 0x6e, 0x48, 0x13, 0x9a, 0x8f, 0xb3, 0x62, 0x98,
	0x92, 0x29, 0xc2, 0x40, 0xa4, 0xd2, 0x92, 0x4a, 0x24, 0xb9, 0x03, 0xed, 0xf0, 0x90, 0xca, 0x09,
	0xf6, 0xda, 0x53, 0x9b, 0x0c, 0x51, 0x86, 0x18, 0x6b, 0x7b, 0xf2, 0x02, 0xe3, 0xfe, 0x36, 0x07,
	0x50, 0x35, 0x2f, 0xd9, 0x84, 0x76, 0x24, 0xb4, 0x90, 0xb6, 0xbb, 0xbe, 0x3c, 0x47, 0xe7, 0x7b,
	0x5b, 0x19, 0x33, 0x30, 0x02, 0xee, 0xef, 0x4d, 0x98, 0xcf, 0x23, 0xe4, 0xca, 0xb4, 0xf7, 0xff,
	0x4f, 0xf5, 0x4f, 0xd6, 0xd4, 0xf9, 0xd0, 0x9a, 0xde, 0x82, 0x96, 0x4c, 0x22, 0x63, 0x38, 0x18,
	0x7c, 0x30, 0xdc, 0x32, 0xd8, 0x6c, 0xd1, 0xfd, 0x67, 0x1e, 0x96, 0xa7, 0xe6, 0x08, 0xd9, 0x84,
	0x79, 0xce, 0xe2, 0xb7, 0xd6, 0xb7, 0xfb, 0xe7, 0x1b, 0x43, 0xde, 0x4b, 0x16, 0xbf, 0x0d, 0x0a,
	0x05, 0xf7, 0x2f, 0x07, 0x9c, 0xec, 0x3f, 0x79, 0x01, 0xad, 0x49, 0xa2, 0xcc, 0xa8, 0xfc, 0xea,
	0x02, 0x8a, 0xde, 0xc6, 0x70, 0x77, 0xd0, 0x08, 0x32, 0x15, 0xb2, 0x0d, 0xce, 0x3b, 0x76, 0xc0,
	0x8c, 0xd3, 0x8f, 0x2f, 0xa2, 0xb6, 0xcf, 0xbe, 0x65, 0x83, 0x46, 0x90, 0xeb, 0x90, 0xd7, 0xd0,
	0x0d, 0x91, 0xf3, 0x94, 0x53, 0x69, 0xea, 0xf1, 0xe4, 0x22, 0x9a, 0xcf, 0x8c, 0xc6, 0xa0, 0x11,
	0x94, 0x7a, 0xee, 0xaf, 0x4d, 0x70, 0xb2, 0xcd, 0x66, 0xdc, 0xda, 0x1e, 0x38, 0x4a, 0xb1, 0x71,
	0x7e, 0xa4, 0x05, 0xb3, 0x96, 0x47, 0xc8, 0x75, 0xe8, 0x84, 0x87, 0x34, 0x8e, 0xb1, 0x78, 0xf6,
	0x2c, 0x97, 0xbd, 0x51, 0x04, 0xc9, 0x16, 0x38, 0x23, 0x1a, 0x8f, 0xf3, 0xa6, 0xb8, 0x74, 0xee,
	0x62, 0xf5, 0x69, 0x3c, 0xb6, 0xdb, 0x65, 0x32, 0xee, 0x26, 0xb4, 0x36, 0x86, 0xbb, 0x33, 0xb2,
	0xfd, 0x0c, 0x40, 0x51, 0x8d, 0x9c, 0x33, 0x9d, 0xcf, 0xda, 0x0a, 0x51, 0x8b, 0xbb, 0xfb, 0xd0,
	0xb5, 0x96, 0xcc, 0xd0, 0xbb, 0x0b, 0x6d, 0xc5, 0x26, 0x31, 0xe5, 0xa6, 0xa4, 0x1f, 0x99, 0x56,
	0x5d, 0xc7, 0x90, 0x8d, 0x90, 0xdb, 0xde, 0x36, 0xa0, 0xfe, 0x02, 0x74, 0xc6, 0xa8, 0x29, 0xe3,
	0xea, 0xd6, 0x53, 0x70, 0xb2, 0x23, 0x90, 0x15, 0x58, 0xea, 0xaf, 0x6d, 0xaf, 0xbf, 0xf9, 0x6e,
	0xfb, 0xc5, 0xf6, 0xce, 0xfe, 0xf6, 0x4a, 0x83, 0x5c, 0x86, 0xe5, 0x3c, 0xb2, 0xba, 0xbe, 0xf3,
	0xea, 0xc1, 0xc6, 0xe0, 0xf5, 0x4a, 0xb3, 0x0c, 0x3d, 0x5c, 0xdf, 0x79, 0x75, 0x2f, 0x0b, 0xcd,
	0xb9, 0x2f, 0xa1, 0x5d, 0x7c, 0xa4, 0x48, 0x1f, 0x96, 0xb8, 0x50, 0xea, 0x8d, 0x38, 0x78, 0x93,
	0xf5, 0xee, 0x99, 0xcf, 0xd9, 0x93, 0x0f, 0x04, 0xc8, 0x58, 0x3b, 0x07, 0x59, 0x07, 0xd4, 0x12,
	0x73, 0x8f, 0x61, 0xa1, 0x7c, 0x89, 0x90, 0x6f, 0xa0, 0x6b, 0x9f, 0xf0, 0x46, 0xf7, 0xea, 0x29,
	0xdd, 0xf5, 0x74, 0xea, 0x29, 0x55, 0x12, 0x88, 0x0f, 0xdd, 0x31, 0x53, 0xba, 0xf6, 0xfa, 0x59,
	0x36, 0xf6, 0x6c, 0xa1, 0xc6, 0x6a, 0x6a, 0x5a, 0x90, 0xfb, 0x67, 0x13, 0xa0, 0x7a, 0x97, 0x5e,
	0xe8, 0xf5, 0x79, 0x0f, 0xba, 0x89, 0x44, 0xa5, 0x4e, 0x7f, 0x41, 0x86, 0x54, 0x85, 0xb4, 0xac,
	0x48, 0x89, 0x3a, 0x39, 0xa2, 0x5a, 0x1f, 0x3a, 0xa2, 0xee, 0x65, 0x77, 0xd9, 0xb4, 0x6f, 0x96,
	0x59, 0xfd, 0x64, 0x43, 0x94, 0xbb, 0x18, 0x8a, 0xaa, 0x43, 0x33, 0x64, 0xcd, 0xe4, 0xbe, 0xff,
	0xfa, 0xee, 0x84, 0xe9, 0xc3, 0x74, 0xe4, 0x85, 0x22, 0xf2, 0x29, 0x93, 0x11, 0x4d, 0x7c, 0x16,
	0x6b, 0x94, 0x07, 0x34, 0x44, 0xe5, 0x2b, 0x19, 0xfa, 0x13, 0xe1, 0x97, 0x57, 0x62, 0xd4, 0xce,
	0xed, 0xbe, 0xff, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x33, 0xae, 0x08, 0xa6, 0x0d, 0x00,
	0x00,
}
