# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ids/ids.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ids/ids.proto',
  package='ids',
  syntax='proto3',
  serialized_options=b'Z\'github.com/airmap/interfaces/src/go/ids',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rids/ids.proto\x12\x03ids\"\x1d\n\x08Operator\x12\x11\n\tas_string\x18\x01 \x01(\t\"\x1e\n\tOperation\x12\x11\n\tas_string\x18\x01 \x01(\t\"\x18\n\x03USS\x12\x11\n\tas_string\x18\x01 \x01(\t\"\x1c\n\x07Tracker\x12\x11\n\tas_string\x18\x01 \x01(\t\"\x1c\n\x07\x43luster\x12\x11\n\tas_string\x18\x01 \x01(\tB)Z\'github.com/airmap/interfaces/src/go/idsb\x06proto3'
)




_OPERATOR = _descriptor.Descriptor(
  name='Operator',
  full_name='ids.Operator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_string', full_name='ids.Operator.as_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=51,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='ids.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_string', full_name='ids.Operation.as_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=83,
)


_USS = _descriptor.Descriptor(
  name='USS',
  full_name='ids.USS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_string', full_name='ids.USS.as_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=109,
)


_TRACKER = _descriptor.Descriptor(
  name='Tracker',
  full_name='ids.Tracker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_string', full_name='ids.Tracker.as_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=139,
)


_CLUSTER = _descriptor.Descriptor(
  name='Cluster',
  full_name='ids.Cluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_string', full_name='ids.Cluster.as_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['Operator'] = _OPERATOR
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['USS'] = _USS
DESCRIPTOR.message_types_by_name['Tracker'] = _TRACKER
DESCRIPTOR.message_types_by_name['Cluster'] = _CLUSTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operator = _reflection.GeneratedProtocolMessageType('Operator', (_message.Message,), {
  'DESCRIPTOR' : _OPERATOR,
  '__module__' : 'ids.ids_pb2'
  # @@protoc_insertion_point(class_scope:ids.Operator)
  })
_sym_db.RegisterMessage(Operator)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'ids.ids_pb2'
  # @@protoc_insertion_point(class_scope:ids.Operation)
  })
_sym_db.RegisterMessage(Operation)

USS = _reflection.GeneratedProtocolMessageType('USS', (_message.Message,), {
  'DESCRIPTOR' : _USS,
  '__module__' : 'ids.ids_pb2'
  # @@protoc_insertion_point(class_scope:ids.USS)
  })
_sym_db.RegisterMessage(USS)

Tracker = _reflection.GeneratedProtocolMessageType('Tracker', (_message.Message,), {
  'DESCRIPTOR' : _TRACKER,
  '__module__' : 'ids.ids_pb2'
  # @@protoc_insertion_point(class_scope:ids.Tracker)
  })
_sym_db.RegisterMessage(Tracker)

Cluster = _reflection.GeneratedProtocolMessageType('Cluster', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTER,
  '__module__' : 'ids.ids_pb2'
  # @@protoc_insertion_point(class_scope:ids.Cluster)
  })
_sym_db.RegisterMessage(Cluster)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
