# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from telemetry import archive_pb2 as telemetry_dot_archive__pb2
from telemetry import report_pb2 as telemetry_dot_report__pb2


class ArchiveStub(object):
    """Archive enables services for querying historical telematic data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryOperationReports = channel.unary_stream(
                '/telemetry.Archive/QueryOperationReports',
                request_serializer=telemetry_dot_archive__pb2.OperationQuery.SerializeToString,
                response_deserializer=telemetry_dot_report__pb2.Report.FromString,
                )


class ArchiveServicer(object):
    """Archive enables services for querying historical telematic data.
    """

    def QueryOperationReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchiveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryOperationReports': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryOperationReports,
                    request_deserializer=telemetry_dot_archive__pb2.OperationQuery.FromString,
                    response_serializer=telemetry_dot_report__pb2.Report.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.Archive', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Archive(object):
    """Archive enables services for querying historical telematic data.
    """

    @staticmethod
    def QueryOperationReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/telemetry.Archive/QueryOperationReports',
            telemetry_dot_archive__pb2.OperationQuery.SerializeToString,
            telemetry_dot_report__pb2.Report.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
